models/TracerStudy.php
<?php

namespace app\models;

use Yii;
use mdm\behaviors\ar\RelationTrait;

/**
 * This is the model class for table "tb_tracer_study".
 *
 * @property integer $id
 * @property string $nim
 * @property string $nama
 * @property string $alamat
 * @property string $no_telepon
 * @property string $email
 * @property string $fakultas
 * @property string $jurusan
 */
class TracerStudy extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    use RelationTrait;

    public static function tableName()
    {
        return 'tb_tracer_study';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'alamat', 'no_telepon', 'email', 'fakultas', 'jurusan','tahun_lulus'], 'required'],
            [['alamat','jenis'], 'string'],
            [['tgl_tracer'],'safe'],
            [['email'], 'email'],
            [['nim','nama_perusahaan','jenis_perusahaan'], 'string', 'max' => 50],
            [['nama', 'email', 'fakultas', 'jurusan'], 'string', 'max' => 100],
            [['no_telepon'], 'string', 'max' => 20],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'nim' => Yii::t('app', 'Nim'),
            'nama' => Yii::t('app', 'Nama'),
            'alamat' => Yii::t('app', 'Alamat'),
            'no_telepon' => Yii::t('app', 'No Telepon'),
            'email' => Yii::t('app', 'Email'),
            'fakultas' => Yii::t('app', 'Fakultas'),
            'jurusan' => Yii::t('app', 'Program Studi'),
        ];
    }

    public function getProdi()
    {
        return $this->hasOne(Prodi::className(), ['idunit' => 'jurusan']);
    }
  
    public function getMahasiswa()
    {
        return $this->hasOne(Mahasiswa::className(), ['nim' => 'nim']);
    }

    public function getNama_prodi()
    {
        return is_null($this->prodi) ? "" : $this->prodi->namaunit;
    }
 public function getFakultass()
    {
        return $this->hasOne(Prodi::className(), ['idunit' => 'fakultas']);
    }

    public function getNama_fakultas()
    {
        return is_null($this->fakultass) ? "" : $this->fakultass->namaunit;
    }
    public function getDetTracerStudy()
    {
        return $this->hasMany(Det_TracerStudy::className(), ['id_tracer' => 'id']);
    }

    public function setDetTracerStudy($value)
    {
        $this->loadRelated('detTracerStudy', $value);
    }
}

controllers/TracerStudyController.php
<?php

namespace app\controllers;

use Yii;
use app\models\TracerStudy;
use app\models\TracerStudySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Prodi as Unit;
use yii\helpers\Json;
use app\models\Mahasiswa;
use app\models\Pertanyaan;
use app\models\Det_TracerStudy;
use yii\base\DynamicModel;

/**
 * TracerStudyController implements the CRUD actions for TracerStudy model.
 */
class TracerStudyController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all TracerStudy models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TracerStudySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,'Tracer Study');

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionIndexSurvey()
    {
        $searchModel = new TracerStudySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,'Survey Kepuasan');

        return $this->render('index-survey', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TracerStudy model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TracerStudy model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
      if(Yii::$app->user->isGuest)
      {
        return $this->redirect(['/site/login']);
      }
      
       $model = new TracerStudy();
      

        if ($model->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            try {
                date_default_timezone_set('Asia/Jakarta');
                $model->detTracerStudy = Yii::$app->request->post('Det_TracerStudy', []);
                $model->tgl_tracer = date('Y-m-d h:n:s');



                if ($model->save()) {
                    $transaction->commit();
                    Yii::$app->session->setFlash('success','Terima Kasih Atas Kesediaan Anda Mengisi Tracer Study Alumni UIN Sunan Ampel');
                    return $this->redirect(['view', 'id' => $model->id]);
                }

                $transaction->rollBack();
                return $this->render('create', [
                    'model' => $model,

                ]);
            } catch (\Exception $ecx) {
                $transaction->rollBack();
                throw $ecx;
            }

            return $this->render('create', [
                'model' => $model,

            ]);
        } else {

            $modelPertanyaan = Pertanyaan::find()->where(['status'=>1,'peruntukan'=>'Tracer Study'])->all();
            $listPertanyaan = [];
            foreach ($modelPertanyaan as $pertanyaan) {
                $detail = new Det_TracerStudy();
                $detail->id_pertanyaan = $pertanyaan->id;
                $listPertanyaan[] = $detail;
            }
            $model->detTracerStudy = $listPertanyaan;

            $mahasiswa = Mahasiswa::find()->where(['nim' => Yii::$app->user->identity->username])->one();
            if (!is_null($mahasiswa)) {
                $model->nim = $mahasiswa->nim;
                $model->nama = $mahasiswa->nama;
                $model->alamat = $mahasiswa->alamat;
                $model->email = $mahasiswa->email;
                $model->no_telepon = $mahasiswa->hp;

                $model->fakultas = $mahasiswa->fakultas->idunit;
                $model->jurusan = $mahasiswa->idunit;
            }


            return $this->render('create', [
                'model' => $model,

            ]);
        }
    }
public function actionSurvey()
    {
    
       $model = new TracerStudy();
      

        if ($model->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            try {
                $model->detTracerStudy = Yii::$app->request->post('Det_TracerStudy', []);
               $model->jenis ='Survey Kepuasan';
               date_default_timezone_set('Asia/Jakarta');
               $model->tgl_tracer = date('Y-m-d h:n:s');




                if ($model->save()) {
                    $transaction->commit();
                    Yii::$app->session->setFlash('success','Terima Kasih Atas Kesediaan Anda Mengisi Tracer Study Alumni UIN Sunan Ampel');
                    return $this->redirect(['/site/index']);
                }

                $transaction->rollBack();
                return $this->render('create', [
                    'model' => $model,

                ]);
            } catch (\Exception $ecx) {
                $transaction->rollBack();
                throw $ecx;
            }

            return $this->render('create', [
                'model' => $model,

            ]);
        } else {

            $modelPertanyaan = Pertanyaan::find()->where(['status'=>1,'peruntukan'=>'Survey Kepuasan'])->all();
            $listPertanyaan = [];
            foreach ($modelPertanyaan as $pertanyaan) {
                $detail = new Det_TracerStudy();
                $detail->id_pertanyaan = $pertanyaan->id;
                $listPertanyaan[] = $detail;
            }
            $model->detTracerStudy = $listPertanyaan;

      

            return $this->render('survey', [
                'model' => $model,

            ]);
        }
    }

    /**
     * Updates an existing TracerStudy model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);


            
        if ($model->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            try {
               $model->detTracerStudy = Yii::$app->request->post('Det_TracerStudy', []);
   



                if ($model->save()) {
                    $transaction->commit();
                    Yii::$app->session->setFlash('success','Terima Kasih Atas Kesediaan Anda Mengisi Tracer Study Alumni UIN Sunan Ampel');
                    return $this->redirect( $model->jenis =='Survey Kepuasan'?['index-survey']:['index']);
                }

                $transaction->rollBack();
                return $this->render('update', [
                    'model' => $model,

                ]);
            } catch (\Exception $ecx) {
                $transaction->rollBack();
                throw $ecx;
            }

            return $this->render('update', [
                'model' => $model,

            ]);
       
      
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionJurusan()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $id = $_POST['depdrop_parents'];
            $data = Unit::find()
                ->select([
                    'id' => 'idunit', 'name' => 'namaunit',
                ])
                ->where(['parentunit' => $id])
                ->asArray()
                ->all();
            foreach ($data as $i => $list) {
                $out[] = ['id' => $list['id'], 'name' => $list['name']];
            }
            return Json::encode(['output' => $out, 'selected' => '']);
        }
        return Json::encode(['output' => '', 'selected' => '']);
    }
    /**
     * Deletes an existing TracerStudy model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */

     public  function actionUploadTracerStudy()
     {

        $model = new DynamicModel(
            [
                'file',
                'fakultas',
                'prodi',    
            ]
        );
        $model->addRule(['file'], 'required');
        $model->addRule(['file'], 'file', ['extensions' => 'xlsx,xls']);
        $model->addRule(['fakultas','prodi'], 'required');
            
        if($model->load(Yii::$app->request->post())){
           


        } 
        return $this->renderAjax('upload-tracer-study',[
            'model' => $model,
        ]);
        


     }
    public function actionDelete($id)
    {

        try {
            $this->findModel($id)->delete();
        } catch (\yii\db\IntegrityException  $e) {
            Yii::$app->session->setFlash('error', "Data Tidak Dapat Dihapus Karena Dipakai Modul Lain");
        }
        return $this->redirect(['index']);
    }

    /**
     * Finds the TracerStudy model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TracerStudy the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TracerStudy::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/tracer-study/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use app\models\Prodi;
use yii\helpers\ArrayHelper;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\TracerStudy */
/* @var $form yii\widgets\ActiveForm */

$fakultas = ArrayHelper::map(
   Prodi::find()->select(['idunit', 'namaunit'])->where(['levelunit' => '2'])->asArray()->all(),
   'idunit',
   'namaunit'
);



?>

<div class="tracer-study-form">

   <div class="x_panel ">
      <div class="x_title">

         <h4>Biodata</h4>
         <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>

         </ul>
         <div class="clearfix"></div>
      </div>

      <div class="x_content">

         <?php $form = ActiveForm::begin(); ?>
         <?= $form->errorSummary($model) ?>
         <!-- ADDED HERE -->

         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('nim') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'nim')->textInput(['maxlength' => true])->label(false) ?></div>
         </div>

         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('nama') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'nama')->textInput(['maxlength' => true])->label(false) ?></div>
         </div>



         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('Alamat') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'alamat')->textarea(['rows' => '6'])->label(false) ?></div>
         </div>


         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('no_telepon') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'no_telepon')->textInput(['maxlength' => true])->label(false) ?></div>
         </div>

         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('email') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'email')->textInput(['maxlength' => true])->label(false) ?></div>
         </div>

         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('tahun_lulus') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'tahun_lulus')->textInput(['maxlength' => true])->label(false) ?></div>
         </div>


         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('fakultas') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'fakultas')->widget(Select2::className(), ['data' => $fakultas, 'options' => ['placeholder' => 'Pilih Fakultas ...']])->label(false) ?></div>
         </div>

         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('jurusan') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'jurusan')->widget(DepDrop::classname(), [
                                       'type' => DepDrop::TYPE_SELECT2,
                                       'data' => [$model->jurusan => $model->nama_prodi],
                                       'options' => ['placeholder' => 'Pilih Program Studi ...'],
                                       'select2Options' => ['pluginOptions' => ['allowClear' => true]],
                                       'pluginOptions' => [
                                          'depends' => ['tracerstudy-fakultas'],
                                          'url' => Url::to(['/tracer-study/jurusan']),
                                          'placeholder' => 'Pilih Program Studi ...',
                                          'initialize' => true,
                                       ],
                                    ])->label(false); ?></div>
         </div>

      </div>
   </div>
   <br>
   <br>
   <br>
   <br>


   <div class="x_panel ">
      <div class="x_title">

         <h4>Pertanyaan</h4>
         <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>

         </ul>
         <div class="clearfix"></div>
      </div>

      <div class="x_content">

         <?php
         $i = 1;
         foreach ($model->detTracerStudy as $detail) {

            ?>
            <div class="row">
               <?= $form->field($detail, "[$i]id_pertanyaan")->hiddenInput()->label(false); ?>

               <label class="col-md-3 col-form-label"> <?= $detail->pertanyaan->pertanyaan ?> </label>
               <div class="col-md-6">
                  <?php
                  if ($detail->pertanyaan->jenis == 1) {

                     ?>
                     <?= $form->field($detail, "[$i]jawaban")->label(false); ?>

                  <?php
                  } else {
                     $jawab = ArrayHelper::map($detail->pertanyaan->jawabans, 'nilai', 'jawaban');

                     ?>

                     <?= $form->field($detail, "[$i]jawaban")->radioList($jawab, ['separator' => '<br/>'])->label(false); ?>


                  <?php

                  }

                  ?>

               </div>
            </div>


            <?php
            $i++;
         }

         ?>

         <br>
         <br>

         <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Simpan'), ['class' => 'btn btn-success']) ?>
         </div>

         <?php ActiveForm::end(); ?>

      </div>

   </div>
</div>

</div>

views/tracer-study/_form_survey.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use app\models\Prodi;
use yii\helpers\ArrayHelper;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\TracerStudy */
/* @var $form yii\widgets\ActiveForm */

$fakultas = ArrayHelper::map(
   Prodi::find()->select(['idunit', 'namaunit'])->where(['=','levelunit','3'])->asArray()->all(),
   'idunit',
   'namaunit'
);



?>

<div class="tracer-study-form">

   <div class="x_panel ">
      <div class="x_title">

         <h4>Biodata</h4>
         <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>

         </ul>
         <div class="clearfix"></div>
      </div>

      <div class="x_content">

         <?php $form = ActiveForm::begin(); ?>
         <?= $form->errorSummary($model) ?>
              </div>
      

  
      <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('jenis_instansi') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'jenis_perusahaan')->dropDownList(["BUMN" => 'BUMN','Pemerintahan' => "Pemerintahan","Swasta"=>"Swasta","Pendidikan"=>"Pendidikan","TNI/POLRI"=>"TNI/POLRI" ],[
            
          
        ])->label(false)?></div></div>

         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('nama_instansi') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'nama_perusahaan')->textInput(['maxlength' => true])->label(false) ?></div>
         </div>

  
  
        
         <!-- ADDED HERE -->
         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('Alamat') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'alamat')->textarea(['rows' => '6'])->label(false) ?></div>
         </div>


         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('no_telepon') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'no_telepon')->textInput(['maxlength' => true])->label(false) ?></div>
         </div>

         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('email') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'email')->textInput(['maxlength' => true])->label(false) ?></div>
         </div>
      
            

         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('nim_karyawan') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'nim')->textInput(['maxlength' => true])->label(false) ?></div>
         </div>

         <div class="row">
            <label class="col-md-3 col-form-label">Nama Karyawan</label>
            <div class="col-md-6"><?= $form->field($model, 'nama')->textInput(['maxlength' => true])->label(false) ?></div>
         </div>






         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('jurusan') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'jurusan')->widget(Select2::className(), ['data' => $fakultas, 'options' => ['placeholder' => 'Pilih Prodi ...']])->label(false) ?></div>
         </div>

         
         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('tahun_lulus') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'tahun_lulus')->textInput(['maxlength' => true])->label(false) ?></div>
         </div>


      
      
   <br>
   <br>
   <br>
   <br>


   <div class="x_panel ">
      <div class="x_title">

         <h4>Tingkat kepuasan pengguna terhadap lulusan program
studi</h4>
         <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>

         </ul>
         <div class="clearfix"></div>
      </div>

      <div class="x_content">

         <?php
         $i = 1;
         foreach ($model->detTracerStudy as $detail) {

            ?>
            <div class="row">
               <?= $form->field($detail, "[$i]id_pertanyaan")->hiddenInput()->label(false); ?>

               <label class="col-md-3 col-form-label"> <?= $detail->pertanyaan->pertanyaan ?> </label>
               <div class="col-md-6">
                  <?php
                  if ($detail->pertanyaan->jenis == 1) {

                     ?>
                     <?= $form->field($detail, "[$i]jawaban")->label(false); ?>

                  <?php
                  } else {
                     $jawab = ArrayHelper::map($detail->pertanyaan->jawabans, 'nilai', 'jawaban');

                     ?>

                     <?= $form->field($detail, "[$i]jawaban")->radioList($jawab, ['separator' => '<br/>'])->label(false); ?>


                  <?php

                  }

                  ?>

               </div>
            </div>


            <?php
            $i++;
         }

         ?>

         <br>
         <br>

         <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Simpan'), ['class' => 'btn btn-success']) ?>
         </div>

         <?php ActiveForm::end(); ?>

      </div>

   </div>
</div>

</div>

views/tracer-study/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TracerStudySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tracer-study-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nim') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'alamat') ?>

    <?= $form->field($model, 'no_telepon') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'fakultas') ?>

    <?php // echo $form->field($model, 'jurusan') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/tracer-study/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\TracerStudy */

$this->title = Yii::t('app', 'Tracer Study');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Daftar Tracer Study'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tracer-study-create">
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel ">
                <div class="x_title">

                    <h3><?= Html::encode($this->title) ?></h3>

                </div>
                <div class="x_content">


                    <?= $this->render('_form', [
                        'model' => $model,


                    ]) ?>

                </div>
            </div>
        </div>
    </div>

</div>

views/tracer-study/survey.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\TracerStudy */

$this->title = Yii::t('app', 'Survey Kepuasan Pengguna Lulusan');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Daftar Tracer Study'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tracer-study-create">
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel ">
                <div class="x_title">

                    <h3><?= Html::encode($this->title) ?></h3>

                </div>
                <div class="x_content">


                    <?= $this->render('_form_survey', [
                        'model' => $model,


                    ]) ?>

                </div>
            </div>
        </div>
    </div>

</div>

views/tracer-study/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\TracerStudy */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Tracer Study',
]) . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Daftar Tracer Study'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="tracer-study-update">
<div class="tracer-study-create">

<div class="row">
    <div class="col-md-12">
        <div class="card ">
            <div class="card-header card-header-rose card-header-icon">
                <div class="card-icon">
                    <i class="material-icons">access_time</i>
                </div>
                <h4 class="card-title"><?= Html::encode($this->title) ?></h4>
            </div>
            <div class="card-body ">

    

    <?= $this->render((( $model->jenis ='Survey Kepuasan')?"_form_survey": '_form'), [
        'model' => $model,
    ]) ?>
    </div>
        </div>
    </div>
</div>

</div>

views/tracer-study/upload-tracer-study.php
<?php
  use yii\widgets\ActiveForm;

  use app\models\Prodi;
use yii\helpers\ArrayHelper;
use kartik\depdrop\DepDrop;
use kartik\select2\Select2;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\TracerStudy */
/* @var $form yii\widgets\ActiveForm */

$fakultas = ArrayHelper::map(
   Prodi::find()->select(['idunit', 'namaunit'])->where(['levelunit' => '2'])->asArray()->all(),
   'idunit',
   'namaunit'
);

  

?>

<h3>Upload Hasil Tracer Study</h3>


<?php $form = ActiveForm::begin(
    [
        'options' => ['enctype' => 'multipart/form-data'],
        'action' => ['upload-tracer-study'],
        'method' => 'post',
    ]

); ?>
        <?= $form->errorSummary($model); ?> <!-- ADDED HERE -->

        <?= $form->field($model, 'file')->fileInput() ?>

        
        <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('fakultas') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'fakultas')->widget(Select2::className(), ['data' => $fakultas, 'options' => ['placeholder' => 'Pilih Fakultas ...']])->label(false) ?></div>
         </div>

         <div class="row">
            <label class="col-md-3 col-form-label"><?= $model->getAttributeLabel('prodi') ?></label>
            <div class="col-md-6"><?= $form->field($model, 'prodi')->widget(DepDrop::classname(), [
                                       'type' => DepDrop::TYPE_SELECT2,
                                       'options' => ['placeholder' => 'Pilih Program Studi ...'],
                                       'select2Options' => ['pluginOptions' => ['allowClear' => true]],
                                       'pluginOptions' => [
                                          'depends' => ['dynamicmodel-fakultas'],
                                          'url' => Url::to(['/tracer-study/jurusan']),
                                          'placeholder' => 'Pilih Program Studi ...',
                                          'initialize' => true,
                                       ],
                                    ])->label(false); ?></div>
         </div>





        <?php ActiveForm::end() ?>